export const BUILDING = {
  name: "RV Uddiipta",
  developer: "RV Nirmaan Private Limited",
  tagline: "Premium 2 & 3 BHK high-rise residences",
  location: "Karmanghat, Hyderabad",
  address: "Sy. No. 66, ZP Road, adjacent to Bhupeshgupta Nagar, Karmanghat",
  acres: 2.2,
  units: 238,
  floors: 10,
  wings: ["A", "B"] as const,
  rera: "P02400004125",
  igbc: "IGBCGH220103",
  clubhouseSqft: 16000,
  greeneryFacingPercent: 65,
  nearby: [
    { label: "LB Nagar Circle", distance: "3.6 km" },
    { label: "Dilsukhnagar", distance: "8.2 km" },
    { label: "Rajiv Gandhi International Airport", distance: "21 km" },
  ],
  amenities: [
    "16,000 sft clubhouse",
    "Indoor swimming pool",
    "Gymnasium",
    "Multipurpose hall",
    "Guest rooms",
    "Walking & jogging track",
    "Cricket pitch",
    "Basketball practice",
    "Children's play area",
    "Meditation zone",
    "24/7 security",
    "Video door phone",
    "EV charging",
    "Solar fencing",
    "STP treated water",
  ],
} as const;
